name: flutter_wasm_test
description: A Flutter project demonstrating how to import WASM code compiled from Rust code
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  wasm_interop: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/add_bg.wasm

